INSERT INTO unidade(descricao) VALUES ('101');
INSERT INTO unidade(descricao) VALUES ('102');
INSERT INTO unidade(descricao) VALUES ('103');
INSERT INTO unidade(descricao) VALUES ('104');
INSERT INTO unidade(descricao) VALUES ('105');
INSERT INTO unidade(descricao) VALUES ('106');
INSERT INTO unidade(descricao) VALUES ('107');
INSERT INTO unidade(descricao) VALUES ('108');
INSERT INTO unidade(descricao) VALUES ('109');
INSERT INTO unidade(descricao) VALUES ('110');
INSERT INTO unidade(descricao) VALUES ('111');
INSERT INTO unidade(descricao) VALUES ('112');
INSERT INTO unidade(descricao) VALUES ('113');
INSERT INTO unidade(descricao) VALUES ('114');
INSERT INTO unidade(descricao) VALUES ('115');
INSERT INTO unidade(descricao) VALUES ('116');
INSERT INTO unidade(descricao) VALUES ('117');
-- INSERT INTO unidade(descricao) VALUES ('117');
INSERT INTO unidade(descricao) VALUES ('118');
INSERT INTO unidade(descricao) VALUES ('119');
INSERT INTO unidade(descricao) VALUES ('120');
INSERT INTO unidade(descricao) VALUES ('121');
INSERT INTO unidade(descricao) VALUES ('122');
INSERT INTO unidade(descricao) VALUES ('123');
INSERT INTO unidade(descricao) VALUES ('124');
INSERT INTO unidade(descricao) VALUES ('125');
INSERT INTO unidade(descricao) VALUES ('126');
INSERT INTO unidade(descricao) VALUES ('127');
INSERT INTO unidade(descricao) VALUES ('128');
INSERT INTO unidade(descricao) VALUES ('129');
INSERT INTO unidade(descricao) VALUES ('130');
INSERT INTO unidade(descricao) VALUES ('131');
INSERT INTO unidade(descricao) VALUES ('132');
INSERT INTO unidade(descricao) VALUES ('201');
INSERT INTO unidade(descricao) VALUES ('202');
-- INSERT INTO unidade(descricao) VALUES ('203');
INSERT INTO unidade(descricao) VALUES ('203');
INSERT INTO unidade(descricao) VALUES ('204');
INSERT INTO unidade(descricao) VALUES ('205');
INSERT INTO unidade(descricao) VALUES ('206');
INSERT INTO unidade(descricao) VALUES ('207');
INSERT INTO unidade(descricao) VALUES ('208');
INSERT INTO unidade(descricao) VALUES ('209');
INSERT INTO unidade(descricao) VALUES ('210');
INSERT INTO unidade(descricao) VALUES ('211');
INSERT INTO unidade(descricao) VALUES ('212');
INSERT INTO unidade(descricao) VALUES ('213');
INSERT INTO unidade(descricao) VALUES ('214');
INSERT INTO unidade(descricao) VALUES ('215');
INSERT INTO unidade(descricao) VALUES ('216');
INSERT INTO unidade(descricao) VALUES ('217');
INSERT INTO unidade(descricao) VALUES ('218');
INSERT INTO unidade(descricao) VALUES ('219');
INSERT INTO unidade(descricao) VALUES ('220');
INSERT INTO unidade(descricao) VALUES ('221');
INSERT INTO unidade(descricao) VALUES ('222');
INSERT INTO unidade(descricao) VALUES ('223');
INSERT INTO unidade(descricao) VALUES ('224');
INSERT INTO unidade(descricao) VALUES ('225');
INSERT INTO unidade(descricao) VALUES ('226');
INSERT INTO unidade(descricao) VALUES ('227');
INSERT INTO unidade(descricao) VALUES ('228');
INSERT INTO unidade(descricao) VALUES ('229');
--INSERT INTO unidade(descricao) VALUES ('230');
INSERT INTO unidade(descricao) VALUES ('230');
INSERT INTO unidade(descricao) VALUES ('231');
INSERT INTO unidade(descricao) VALUES ('232');
INSERT INTO unidade(descricao) VALUES ('301');
--INSERT INTO unidade(descricao) VALUES ('302');
INSERT INTO unidade(descricao) VALUES ('302');
INSERT INTO unidade(descricao) VALUES ('303');
INSERT INTO unidade(descricao) VALUES ('304');
INSERT INTO unidade(descricao) VALUES ('305');
INSERT INTO unidade(descricao) VALUES ('306');
INSERT INTO unidade(descricao) VALUES ('307');
INSERT INTO unidade(descricao) VALUES ('308');
INSERT INTO unidade(descricao) VALUES ('309');
INSERT INTO unidade(descricao) VALUES ('310');
INSERT INTO unidade(descricao) VALUES ('311');
INSERT INTO unidade(descricao) VALUES ('312');
INSERT INTO unidade(descricao) VALUES ('313');
INSERT INTO unidade(descricao) VALUES ('314');
INSERT INTO unidade(descricao) VALUES ('315');
INSERT INTO unidade(descricao) VALUES ('316');
INSERT INTO unidade(descricao) VALUES ('317');
INSERT INTO unidade(descricao) VALUES ('318');
INSERT INTO unidade(descricao) VALUES ('319');
INSERT INTO unidade(descricao) VALUES ('320');
INSERT INTO unidade(descricao) VALUES ('321');
INSERT INTO unidade(descricao) VALUES ('322');
INSERT INTO unidade(descricao) VALUES ('323');
INSERT INTO unidade(descricao) VALUES ('324');
INSERT INTO unidade(descricao) VALUES ('325');
INSERT INTO unidade(descricao) VALUES ('326');
INSERT INTO unidade(descricao) VALUES ('327');
INSERT INTO unidade(descricao) VALUES ('328');
INSERT INTO unidade(descricao) VALUES ('329');
INSERT INTO unidade(descricao) VALUES ('330');
INSERT INTO unidade(descricao) VALUES ('331');
INSERT INTO unidade(descricao) VALUES ('332');
INSERT INTO unidade(descricao) VALUES ('401');
INSERT INTO unidade(descricao) VALUES ('402');
INSERT INTO unidade(descricao) VALUES ('403');
INSERT INTO unidade(descricao) VALUES ('404');
INSERT INTO unidade(descricao) VALUES ('405');
INSERT INTO unidade(descricao) VALUES ('406');
--INSERT INTO unidade(descricao) VALUES ('406');
INSERT INTO unidade(descricao) VALUES ('407');
INSERT INTO unidade(descricao) VALUES ('408');
INSERT INTO unidade(descricao) VALUES ('409');
INSERT INTO unidade(descricao) VALUES ('410');
--INSERT INTO unidade(descricao) VALUES ('411');
INSERT INTO unidade(descricao) VALUES ('411');
INSERT INTO unidade(descricao) VALUES ('412');
INSERT INTO unidade(descricao) VALUES ('413');
INSERT INTO unidade(descricao) VALUES ('414');
INSERT INTO unidade(descricao) VALUES ('415');
INSERT INTO unidade(descricao) VALUES ('416');
INSERT INTO unidade(descricao) VALUES ('417');
INSERT INTO unidade(descricao) VALUES ('418');
INSERT INTO unidade(descricao) VALUES ('419');
INSERT INTO unidade(descricao) VALUES ('420');
INSERT INTO unidade(descricao) VALUES ('421');
INSERT INTO unidade(descricao) VALUES ('422');
INSERT INTO unidade(descricao) VALUES ('423');
INSERT INTO unidade(descricao) VALUES ('424');
INSERT INTO unidade(descricao) VALUES ('425');
INSERT INTO unidade(descricao) VALUES ('426');
INSERT INTO unidade(descricao) VALUES ('427');
INSERT INTO unidade(descricao) VALUES ('428');
INSERT INTO unidade(descricao) VALUES ('429');
INSERT INTO unidade(descricao) VALUES ('430');
INSERT INTO unidade(descricao) VALUES ('431');
INSERT INTO unidade(descricao) VALUES ('432');
INSERT INTO unidade(descricao) VALUES ('501');
INSERT INTO unidade(descricao) VALUES ('502');
INSERT INTO unidade(descricao) VALUES ('503');
INSERT INTO unidade(descricao) VALUES ('504');
INSERT INTO unidade(descricao) VALUES ('505');
INSERT INTO unidade(descricao) VALUES ('506');
INSERT INTO unidade(descricao) VALUES ('507');
INSERT INTO unidade(descricao) VALUES ('508');
INSERT INTO unidade(descricao) VALUES ('509');
INSERT INTO unidade(descricao) VALUES ('510');
INSERT INTO unidade(descricao) VALUES ('511');
INSERT INTO unidade(descricao) VALUES ('512');
INSERT INTO unidade(descricao) VALUES ('513');
INSERT INTO unidade(descricao) VALUES ('514');
INSERT INTO unidade(descricao) VALUES ('515');
INSERT INTO unidade(descricao) VALUES ('516');
INSERT INTO unidade(descricao) VALUES ('517');
INSERT INTO unidade(descricao) VALUES ('518');
INSERT INTO unidade(descricao) VALUES ('519');
INSERT INTO unidade(descricao) VALUES ('520');
INSERT INTO unidade(descricao) VALUES ('521');
INSERT INTO unidade(descricao) VALUES ('522');
INSERT INTO unidade(descricao) VALUES ('523');
--INSERT INTO unidade(descricao) VALUES ('524');
INSERT INTO unidade(descricao) VALUES ('524');
INSERT INTO unidade(descricao) VALUES ('525');
INSERT INTO unidade(descricao) VALUES ('526');
INSERT INTO unidade(descricao) VALUES ('527');
INSERT INTO unidade(descricao) VALUES ('528');
INSERT INTO unidade(descricao) VALUES ('529');
INSERT INTO unidade(descricao) VALUES ('530');
--INSERT INTO unidade(descricao) VALUES ('531');
INSERT INTO unidade(descricao) VALUES ('531');
INSERT INTO unidade(descricao) VALUES ('601');
INSERT INTO unidade(descricao) VALUES ('602');
INSERT INTO unidade(descricao) VALUES ('603');
INSERT INTO unidade(descricao) VALUES ('604');
INSERT INTO unidade(descricao) VALUES ('605');
INSERT INTO unidade(descricao) VALUES ('606');
INSERT INTO unidade(descricao) VALUES ('607');
INSERT INTO unidade(descricao) VALUES ('608');
INSERT INTO unidade(descricao) VALUES ('609');
INSERT INTO unidade(descricao) VALUES ('610');
INSERT INTO unidade(descricao) VALUES ('611');
INSERT INTO unidade(descricao) VALUES ('612');
INSERT INTO unidade(descricao) VALUES ('613');
INSERT INTO unidade(descricao) VALUES ('614');
INSERT INTO unidade(descricao) VALUES ('615');
INSERT INTO unidade(descricao) VALUES ('616');
INSERT INTO unidade(descricao) VALUES ('617');
INSERT INTO unidade(descricao) VALUES ('618');
INSERT INTO unidade(descricao) VALUES ('619');
INSERT INTO unidade(descricao) VALUES ('620');
INSERT INTO unidade(descricao) VALUES ('621');
INSERT INTO unidade(descricao) VALUES ('622');
INSERT INTO unidade(descricao) VALUES ('623');
INSERT INTO unidade(descricao) VALUES ('624');
INSERT INTO unidade(descricao) VALUES ('625');
INSERT INTO unidade(descricao) VALUES ('626');
INSERT INTO unidade(descricao) VALUES ('627');
INSERT INTO unidade(descricao) VALUES ('628');
INSERT INTO unidade(descricao) VALUES ('629');
INSERT INTO unidade(descricao) VALUES ('630');
INSERT INTO unidade(descricao) VALUES ('631');
INSERT INTO unidade(descricao) VALUES ('632');
INSERT INTO unidade(descricao) VALUES ('K-0532');
INSERT INTO unidade(descricao) VALUES ('VG-001');
INSERT INTO unidade(descricao) VALUES ('VG-002 - APTO 531');
INSERT INTO unidade(descricao) VALUES ('VG-003');
INSERT INTO unidade(descricao) VALUES ('VG-004 - APTO 423');
INSERT INTO unidade(descricao) VALUES ('VG-005');
INSERT INTO unidade(descricao) VALUES ('VG-006');
INSERT INTO unidade(descricao) VALUES ('VG-007 - APTO 223');
INSERT INTO unidade(descricao) VALUES ('VG-008 – APTO 418');
INSERT INTO unidade(descricao) VALUES ('VG-009 - APTO 427');
INSERT INTO unidade(descricao) VALUES ('VG-010 - APTO 520');
INSERT INTO unidade(descricao) VALUES ('VG-011 - APTO 318');
INSERT INTO unidade(descricao) VALUES ('VG-012');
INSERT INTO unidade(descricao) VALUES ('VG-013 - APTO 214');
INSERT INTO unidade(descricao) VALUES ('VG-014');
INSERT INTO unidade(descricao) VALUES ('VG-015 – APTO 310');
INSERT INTO unidade(descricao) VALUES ('VG-016 - APTO 210');
INSERT INTO unidade(descricao) VALUES ('VG-017 - APTO 311');
INSERT INTO unidade(descricao) VALUES ('VG-018 - APTO 506');
INSERT INTO unidade(descricao) VALUES ('VG-019');
INSERT INTO unidade(descricao) VALUES ('VG-020');
INSERT INTO unidade(descricao) VALUES ('VG-021 – APTO 102');
INSERT INTO unidade(descricao) VALUES ('VG-022');
INSERT INTO unidade(descricao) VALUES ('VG-023 - APTO 312');
INSERT INTO unidade(descricao) VALUES ('VG-024');
INSERT INTO unidade(descricao) VALUES ('VG-025 - APTO 308');
INSERT INTO unidade(descricao) VALUES ('VG-026 - APTO 421');
INSERT INTO unidade(descricao) VALUES ('VG-027');
INSERT INTO unidade(descricao) VALUES ('VG-028');
INSERT INTO unidade(descricao) VALUES ('VG-029 – APTO 405');
INSERT INTO unidade(descricao) VALUES ('VG-031 - APTO 228');
INSERT INTO unidade(descricao) VALUES ('VG-032 - APTO 326');
INSERT INTO unidade(descricao) VALUES ('VG-034 - APTO 420');
INSERT INTO unidade(descricao) VALUES ('VG-035');
INSERT INTO unidade(descricao) VALUES ('VG-037 - APTO 329');
INSERT INTO unidade(descricao) VALUES ('VG-038');
INSERT INTO unidade(descricao) VALUES ('VG-040 - APTO 319');
INSERT INTO unidade(descricao) VALUES ('VG-041');
INSERT INTO unidade(descricao) VALUES ('VG-043 - APTO 523');
INSERT INTO unidade(descricao) VALUES ('VG-044 - APTO 424');
INSERT INTO unidade(descricao) VALUES ('VG-060');
INSERT INTO unidade(descricao) VALUES ('VG-099');
INSERT INTO unidade(descricao) VALUES ('VG-100');
INSERT INTO unidade(descricao) VALUES ('VG-166');
INSERT INTO unidade(descricao) VALUES ('VG-167');
INSERT INTO unidade(descricao) VALUES ('VG-217 - APTO 408');
INSERT INTO unidade(descricao) VALUES ('VG-243 - APTO 412');
INSERT INTO unidade(descricao) VALUES ('VG-244 - APTO 413');
INSERT INTO unidade(descricao) VALUES ('VG-245 - APTO 110');
INSERT INTO unidade(descricao) VALUES ('VG-246 - APTO 317');
INSERT INTO unidade(descricao) VALUES ('VG-247 - APTO 325');
INSERT INTO unidade(descricao) VALUES ('VG-248 - APTO 431');
INSERT INTO unidade(descricao) VALUES ('VG-249 - APTO 321');
INSERT INTO unidade(descricao) VALUES ('VG-250 - APTO 121');
INSERT INTO unidade(descricao) VALUES ('VG-262 – APTO 332');
INSERT INTO unidade(descricao) VALUES ('VG-263 - APTO 428');
INSERT INTO unidade(descricao) VALUES ('VG-264 - APTO 528');
INSERT INTO unidade(descricao) VALUES ('VG-281');
--INSERT INTO unidade(descricao) VALUES ('VG-281');
INSERT INTO unidade(descricao) VALUES ('VG-282 - APTO 130');
